### ISSUE TITLE
Operator Onboarding: 🐹 Quokka Stake 

### ISSUE THREAD

**Issue by freak12techno** [cryptocrew-validators/relayer-feegrant-wg#33]
## Operator name & memo
Plase set your relayer name (required) and optionally memo.
- Operator Name: 🐹 Quokka Stake
- Memo: Relayed with ❤️ by 🐹 Quokka Stake

## IBC Path Selection
Please specify the IBC path (e.g., `cosmoshub-osmosis`) you want to be added to:
- IBC Path: cosmoshub-osmosis

## Chain Account Information
Please provide your account information for each chain in the selected IBC path:
- Cosmoshub Account: cosmos17ndx5qfku28ymxgmq6zq4a6d02dvpfjj5yu8j9
- Counterparty Account: osmo17ndx5qfku28ymxgmq6zq4a6d02dvpfjjul0hyh

## Contact Information
Please provide at least one of the following for contact purposes:
- Discord Handle: @freak12techno
- Telegram Handle: @freak12techno

**Comment by clemensgg** [comment]
fixing an issue with workflow write permissions, hang on pls :)

**Comment by clemensgg** [comment]
actually it could be that the changes have been committed to my account since i re-triggered the workflow. I'll open the PR for you
