### ISSUE TITLE
Operator Onboarding: Cosmos Spaces

### ISSUE THREAD

**Issue by CosmosSpaces** [cryptocrew-validators/relayer-feegrant-wg#9]
## Operator name & memo
Plase set your relayer name (required) and optionally memo.
- Operator Name: Cosmos Spaces
- Memo: relayed by Cosmos Spaces

## IBC Path Selection
Please specify the IBC path (e.g., `cosmoshub-osmosis`) you want to be added to:
- IBC Path: cosmoshub-osmosis

## Chain Account Information
Please provide your account information for each chain in the selected IBC path:
- Cosmoshub Account: cosmos1ks0qeq9vyt9l7vgasaajd49ff0k8klure6ez4n
- Counterparty Account: osmo1ks0qeq9vyt9l7vgasaajd49ff0k8klur3p2jrp

## Contact Information
Please provide at least one of the following for contact purposes:
- Discord Handle: .tricky_.
- Telegram Handle: Char1esBark1ey

**Comment by clemensgg** [comment]
@CosmosSpaces this looks good to me, please open a PR
